#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.

# Run scripts in /etc/rc.local.d directory
run-parts /etc/rc.local.d

exit 0