#!/bin/bash

[ ! -f $target/lib/systemd/system/docker.service ] && exit 0

# Make /etc/default/docker work
sed -i '/^ExecStart=/s/$/ $DOCKER_OPTS/' $target/lib/systemd/system/docker.service
sed -i 's%^ExecStart=.*%EnvironmentFile=/etc/default/docker\n&%' $target/lib/systemd/system/docker.service

# Start Docker even if we have no network connection
sed -i 's/^After=network.target/After=local-fs.target/' $target/lib/systemd/system/docker.service