#!/bin/bash

echo "$FAI_ROOT/etc/default/grub"

cat $FAI_ROOT/etc/default/grub

# Enable Swap/Memory accounting / Enable Apparmor
sed -ri 's/^(GRUB_CMDLINE_LINUX=.*)"$/\1 cgroup_enable=memory swapaccount=1 apparmor=1 security=apparmor"/' $FAI_ROOT/etc/default/grub
