#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

echo $TIMEZONE > $target/etc/timezone

if [ -L $target/etc/localtime ] ; then
    ln -sf /usr/share/zoneinfo/${TIMEZONE} $target/etc/localtime
else
    cp -f /usr/share/zoneinfo/${TIMEZONE} $target/etc/localtime
fi

if [ -f $target/etc/hosts.orig ] ; then
    mv $target/etc/hosts.orig $target/etc/hosts
fi
if [ -n "$IPADDR" ] ; then
    ifclass DHCPC || ainsl -s /etc/hosts "$IPADDR $HOSTNAME.$DOMAIN $HOSTNAME"
else
    ifclass DHCPC && ainsl -s /etc/hosts "127.0.0.1 $HOSTNAME"
fi
fcopy -iM /etc/hosts /etc/motd

# make /root accessible only by root
chmod -c 0700 $target/root
chown -c root:root $target/root
# copy default dotfiles for root account
fcopy -ir /root

# use tmpfs for /tmp if not defined in disk_config
if ! grep -Pq '\s/tmp\s' $target/etc/fstab; then
    ainsl /etc/fstab "tmpfs     /tmp tmpfs     nodev,nosuid,size=50%,mode=1777   0    0"
fi
chmod -c 1777 ${target}/tmp
chown -c 0:0  ${target}/tmp

# add additional user account
if [ -n "$username" ]; then
    if ! $ROOTCMD getent passwd $username ; then
		$ROOTCMD adduser --disabled-login --gecos "$username user" $username
		$ROOTCMD usermod -p "$USERPW" $username

		for g in $groups; do
		    $ROOTCMD adduser $username $g
		done
    fi
fi

fcopy -M /etc/default/grub

$ROOTCMD update-grub

fcopy -m root,root,0755 /etc/rc.local
fcopy -m root,root,0755 /etc/rc.local.d/99-reboot_once

exit $error