#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# add additional user account
if [ -n "$username" ]; then
    if ! $ROOTCMD getent passwd $username ; then
		$ROOTCMD adduser --disabled-login --gecos "$username user" $username
		$ROOTCMD usermod -p "$USERPW" $username

		for g in $groups; do
		    $ROOTCMD adduser $username $g
		done
    fi
fi