#!/usr/bin/expect -f

set timeout 5

set passphrase "$env(SIGNING_PASSWORD)"

spawn reprepro -b /var/www/repos/apt/debian $argv

expect {
    timeout                         {exit 0}
    "Please enter the passphrase*"  {send -- "$passphrase\r";
                                     send_user " *** entering passphrase ***";
                                     exp_continue}
}

set returnvalues [wait]
set exitcode [lindex $returnvalues 3]
exit $exitcode