#!/usr/bin/expect -f

set timeout 5

set passphrase "$env(SIGNING_PASSWORD)"

spawn reprepro -b /var/www/repos/apt/debian [lindex $argv 0] [lindex $argv 1] [lindex $argv 2] [lindex $argv 3]

expect {
    timeout                     {exit 0}
    "Please enter passphrase*"  {send -- "$passphrase\r";
                                 send_user " *** entering passphrase ***";
                                 exp_continue}
}

set returnvalues [wait]
set exitcode [lindex $returnvalues 3]
exit $exitcode