#! /bin/bash
#convert docker image to basefile for intallation

docker_pull_image() {
    echo "Downloading docker images "
    docker pull $repo
}

docker_run() {
    container_id=`docker run -d $repo`
}

tarit() {
    echo "Compressing basefile ..."
    docker export $container_id | $zip > $target.$ext
}

cleanup() {
    docker rm $container_id
}

mk_dist_img() {
    docker_pull_image
    docker_run
    tarit
    cleanup
}

prtdists() {
    echo "Available Linux distritubtions:
    STRETCH64
"
}

usage() {

    cat <<EOF
docker2basefile, create minimal base files for a Linux distritubtion from docker image
   Copyright (C) 2019 by slpcat
Usage: dockerbasefile [OPTION] ... DISTRIBUTION
   -s                   Show list of supported linux distributions
   -z                   Use gzip for compressing the tar file.
   -J                   Use xz for compressing the tar file.
   -h                   Print help.
 Usage example: docker-basefile -J STRETCH64
 This will create a STRETCH64.tar.xz basefile.
EOF
    exit 0
}

# main routine

ext=tar
zip=cat
cleanup=1

while getopts shzJd:f: opt ; do
    case "$opt" in
        f) export ARCH=$OPTARG ;;
        z) zip="gzip -9"; ext=tar.gz ;;
        J) zip="xz -8 -T 0" ext=tar.xz ;;
        h) usage ;;
        s) prtdists ; exit 0;;
        ?) exit 3 ;; # error in option parsing
    esac
done
shift $(($OPTIND - 1))

target=$1 # also the name of the output file
repo=

[ -z "$target" ] && usage
case "$target" in
    STRETCH64)
        repo=debian:stretch-slim
        mk_dist_img
        ;;
    LION*)
        debgeneric $target $MIRROR_DEEPIN ;;
    *) echo "Unknown distribution. Aborting."
       prtdists
       exit 99 ;;
esac