#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

#mkdir -p /var/www/repos/apt/debian
#cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/000- debian.conf

$ROOTCMD gpg --list-keys

cat >$target/registry <<EOF
     %echo Generating a basic OpenPGP key
     Key-Type: DSA
     Key-Length: 1024
     Subkey-Type: ELG-E
     Subkey-Length: 1024
     Name-Real: Registry
     Expire-Date: 0
     Passphrase:
     %commit
     %echo done
EOF

sed -ie 's/Passphrase:/Passphrase: '${ROOTPW}'/' $target/registry

$ROOTCMD gpg --batch --generate-key registry

ls -la $target

rm -f $target/registry $target/registrye

key_id=$($ROOTCMD gpg --list-keys --keyid-format=short registry | grep pub | grep -o -P '(?<=/)[A-Z0-9]{8}' | head -1)

#mkdir -p $target/var/www/repos/apt/debian

ls -la $target/var/www/repos/apt/debian

echo "0"

ls -la $target/var/www/repos/apt/debian/distributions

echo "1"

$ROOTCMD gpg --armor --output $target/var/www/repos/apt/debian/registry.gpg.key --export $key_id

echo "A"

ls -la 

echo "B"

ls -la $target

echo "C"

$ROOTCMD reprepro -b $target/var/www/repos/apt/debian export

#echo "G"

#

#
#
#
#gpg --armor --output dbr.gpg.key --export 77410535536CEE1CE5386FDEBE66BE3CB723638B
#
#
#
#mkdir -p /var/www/repos/apt/debian
#cp /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-available/debian.conf
#
#/usr/sbin/a2ensite debian.conf
#
#mkdir -p /var/www/repos/apt/debian/conf
#
#mkdir -p /var/www/repos/apt/Debian
#
#gpg --armor --output /var/www/repos/apt/Debian/dbr.gpg.key --export repository
#
#/var/www/repos/apt/Debian/dbr.gpg.key.
#
#/var/www/repos/apt/debian/conf/distributions
#
#/var/www/repos/apt/debian/conf/override.dbr
#
#reprepro --ask-passphrase export
#


exit $error
