#!/bin/bash

ifclass OS-64 || exit 0

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD gpg --list-keys

cat > $target/root/.gnupg/gpg-agent.conf <<-EOF
default-cache-ttl 46000
pinentry-program /usr/bin/pinentry
allow-preset-passphrase
EOF

cat > $target/registry <<-EOF
     %echo Generating a basic OpenPGP key
     Key-Type: DSA
     Key-Length: 1024
     Subkey-Type: ELG-E
     Subkey-Length: 1024
     Name-Real: Registry
     Expire-Date: 0
     Passphrase: ${ROOTPW}
     %commit
     %echo done
EOF

$ROOTCMD gpg --batch --generate-key registry && rm $target/registry

sub_key=$($ROOTCMD gpg --with-colons --keyid-format=short --list-keys registry | grep sub | head -1 | cut -d':' -f5)

$ROOTCMD gpg-agent --daemon
$ROOTCMD gpg-connect-agent reloadagent /bye

$ROOTCMD /usr/lib/gnupg/gpg-preset-passphrase -c ${sub_key} <<EOF
${ROOTPW}
EOF

mkdir -p $target/var/www/repos/apt/debian/conf

cat > $target/var/www/repos/apt/debian/conf/override.buster <<EOF
buster Priority optional
buster Section net
EOF

cat > $target/var/www/repos/apt/debian/conf/distributions <<-EOF
Origin: OS-64
Codename: buster
Architectures: amd64 arm64
Components: main
Description: OS-64 REGISTRY
SignWith: ${sub_key}
DebOverride: override.buster
EOF

cat > $target/var/www/repos/apt/debian/conf/options <<-EOF
verbose
ask-passphrase
EOF

$ROOTCMD gpg --armor --output /var/www/repos/apt/debian/registry.gpg.key --export $sub_key

#echo "0"

#cat $target/root/.gnupg/gpg-agent.conf

echo "A"

# cache paraphrase so next command does not need it
$ROOTCMD \
     echo X > stub_doc && \
     gpg --pinentry-mode=loopback --passphrase=${ROOTPW} --output stub_doc.sig --sign stub_doc && \
     reprepro --ask-passphrase -b /var/www/repos/apt/debian export && \
     rm -f $target/stub_doc $target/stub_doc.sig

echo "B"

exit $error
