#!bin/bash

$ROOTCMD dpkg --clear-avail 

$ROOTCMD apt-get install systemd-sysv- initscripts insserv startpar sysv-rc sysvinit-core

# If rcS.conf is not removed, FAI will be started twice.
$ROOTCMD rm -v /etc/init/rcS.conf

$ROOTCMD ln -f /bin/true /sbin/initctl
