#!/bin/bash

if ifclass STRETCH64 ; then
	distro="debian"
	codename="stretch"
fi

if ifclass -o STRETCH64 ; then
	cat > $FAI_ROOT/etc/apt/sources.list <<- EOF
		deb http://ftp.debian.org/debian/ $codename main contrib non-free
		deb http://ftp.debian.org/debian/ $codename-updates main contrib non-free
		deb http://ftp.debian.org/debian/ $codename-backports main contrib non-free
		deb http://security.debian.org/ $codename/updates main contrib non-free
	EOF
fi

ifclass SMTT_BASE && \
echo "deb https://reposmtt.smartmatic.net:8443/debian /" > $FAI_ROOT/etc/apt/sources.list.d/reposmtt.list

ifclass DOCKER && \
echo "deb [arch=amd64] https://download.docker.com/linux/$distro $codename edge" > $FAI_ROOT/etc/apt/sources.list.d/docker.list

ifclass CHROME && \
echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > $FAI_ROOT/etc/apt/sources.list.d/google-chrome.list

if ifclass MONGODB ; then
	if [ $distro = "debian" ] ; then
		mongo_dist="main"
	elif [ $distro = "ubuntu" ] ; then
		mongo_dist="universe"
	fi
	echo "deb http://repo.mongodb.org/apt/$distro $codename/mongodb-org/3.2 $mongo_dist" > $FAI_ROOT/etc/apt/sources.list.d/mongodb-org.list
fi

exit 0
